### ISSUE TITLE
May want to add a version pin / dependency on `htmlwidgets`

### ISSUE THREAD

**Issue by colearendt** [RinteRface/connectViz#5]
I did not dive into the version dependency graph here, but got this error message and needed to resolve by installing a later version of `htmlwidgets`

```
Error: object ‘JSEvals’ is not exported by 'namespace:htmlwidgets'
Execution halted
ERROR: lazy loading failed for package ‘connectViz’
* removing ‘/usr/home/cole/connect-usage/renv/staging/1/connectViz’
```

**Comment by pvictor** [comment]
Sorry that's on me, `{apexcharter}` require `{htmlwidgets}` >= 1.5.3.
Fixed on GitHub, soon on CRAN.
