### ISSUE TITLE
Whitespace issues in warning

### ISSUE THREAD

**Issue by pat-s** [RinteRface/connectViz#9]
```
You are using a newer version of RStudio Connect(2022.02.0) than was tested (2021.12.1).Most APIs should function as expected.
```

Between the dot and "most" and the first bracket.

The first sentence could potentially be rephrased as "You are using a newer version of RStudio Connect (2022.02.0) than currently supported (2021.12.1)"

**Comment by DivadNojnarg** [comment]
Hi Pat, 

this message is raised by {connectapi}.

**Comment by pat-s** [comment]
👍 https://github.com/rstudio/connectapi/issues/147
